/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CryptoWalletService } from "../cryptoWallet.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CryptoWalletCreateInput } from "./CryptoWalletCreateInput";
import { CryptoWallet } from "./CryptoWallet";
import { CryptoWalletFindManyArgs } from "./CryptoWalletFindManyArgs";
import { CryptoWalletWhereUniqueInput } from "./CryptoWalletWhereUniqueInput";
import { CryptoWalletUpdateInput } from "./CryptoWalletUpdateInput";
import { TransactionFindManyArgs } from "../../transaction/base/TransactionFindManyArgs";
import { Transaction } from "../../transaction/base/Transaction";
import { TransactionWhereUniqueInput } from "../../transaction/base/TransactionWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CryptoWalletControllerBase {
  constructor(
    protected readonly service: CryptoWalletService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CryptoWallet })
  @nestAccessControl.UseRoles({
    resource: "CryptoWallet",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCryptoWallet(
    @common.Body() data: CryptoWalletCreateInput
  ): Promise<CryptoWallet> {
    return await this.service.createCryptoWallet({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        walletAddress: true,
        balance: true,
        currency: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CryptoWallet] })
  @ApiNestedQuery(CryptoWalletFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CryptoWallet",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async cryptoWallets(@common.Req() request: Request): Promise<CryptoWallet[]> {
    const args = plainToClass(CryptoWalletFindManyArgs, request.query);
    return this.service.cryptoWallets({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        walletAddress: true,
        balance: true,
        currency: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CryptoWallet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CryptoWallet",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async cryptoWallet(
    @common.Param() params: CryptoWalletWhereUniqueInput
  ): Promise<CryptoWallet | null> {
    const result = await this.service.cryptoWallet({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        walletAddress: true,
        balance: true,
        currency: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CryptoWallet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CryptoWallet",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCryptoWallet(
    @common.Param() params: CryptoWalletWhereUniqueInput,
    @common.Body() data: CryptoWalletUpdateInput
  ): Promise<CryptoWallet | null> {
    try {
      return await this.service.updateCryptoWallet({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          walletAddress: true,
          balance: true,
          currency: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CryptoWallet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CryptoWallet",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCryptoWallet(
    @common.Param() params: CryptoWalletWhereUniqueInput
  ): Promise<CryptoWallet | null> {
    try {
      return await this.service.deleteCryptoWallet({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          walletAddress: true,
          balance: true,
          currency: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/transactions")
  @ApiNestedQuery(TransactionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Transaction",
    action: "read",
    possession: "any",
  })
  async findTransactions(
    @common.Req() request: Request,
    @common.Param() params: CryptoWalletWhereUniqueInput
  ): Promise<Transaction[]> {
    const query = plainToClass(TransactionFindManyArgs, request.query);
    const results = await this.service.findTransactions(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        amount: true,
        transactionType: true,
        status: true,

        cryptoWallet: {
          select: {
            id: true,
          },
        },

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/transactions")
  @nestAccessControl.UseRoles({
    resource: "CryptoWallet",
    action: "update",
    possession: "any",
  })
  async connectTransactions(
    @common.Param() params: CryptoWalletWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        connect: body,
      },
    };
    await this.service.updateCryptoWallet({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/transactions")
  @nestAccessControl.UseRoles({
    resource: "CryptoWallet",
    action: "update",
    possession: "any",
  })
  async updateTransactions(
    @common.Param() params: CryptoWalletWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        set: body,
      },
    };
    await this.service.updateCryptoWallet({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/transactions")
  @nestAccessControl.UseRoles({
    resource: "CryptoWallet",
    action: "update",
    possession: "any",
  })
  async disconnectTransactions(
    @common.Param() params: CryptoWalletWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        disconnect: body,
      },
    };
    await this.service.updateCryptoWallet({
      where: params,
      data,
      select: { id: true },
    });
  }
}
